### ISSUE TITLE
Github Page 前端架設

### ISSUE THREAD

**Issue by nu1lspaxe** [nu1lspaxe/blackjack#22]

**Comment by junxiangzhan** [comment]
Github Page Link: https://nu1lspaxe.github.io/blackjack/
Or checking on repo's [**Developments**](https://github.com/nu1lspaxe/blackjack/deployments).

Github Page will deploy from branch: [gh-pages](https://github.com/nu1lspaxe/blackjack/tree/gh-pages)

**Comment by junxiangzhan** [comment]
Github Page Link: https://nu1lspaxe.github.io/blackjack/
Or checking on repo's [Developments](https://github.com/nu1lspaxe/blackjack/deployments).

Github Page will deploy from branch: [gh-pages](https://github.com/nu1lspaxe/blackjack/tree/gh-pages)
